GHP-2202-GraceFull/GraceFull

- client/store/allProducts.js
- client/store/index.js
- client/store/subreducer.js
Create all products reducer. Should be able to pull all products data from the thunk.
> All products subreducer

- script/seed.js
- server/db/index.js
- server/db/models/Product.js
Create a products model with a title*, description*, price*, quantity (defaults to 0), and image url (default photo) fields. Set up a seed file that seeds database with empty Users model and Products model with 3 instances of dummy data.
> Sequelize create products model

- package.json
- server/api/index.js
- server/api/products.js
Created route for all products
> NC - Route - All Products

- client/Routes.js
- client/components/AllProducts.js
- client/components/Navbar.js
all products react component rendering!
> all products rendering

- package.json
- server/api/products.js
create singleProduct express route to pull single Product data from the database
> singleProduct route complete

- client/store/index.js
- client/store/singleProduct.js
- package.json
Added sub-reducer for single product
> subreducer single product

- client/components/AllProducts.js
Added additional button for high to low sorting
> high to low added

- client/components/AddToCart.js
- client/components/AllProducts.js
- client/components/SingleProduct.js
- client/store/addToCart.js
- client/store/index.js
add to cart subreducer ready to be checked
> Add to cart

- client/Routes.js
- client/components/Cart.js
- client/components/Navbar.js
- client/components/SingleProduct.js
- client/components/cartexamplecode.js
- client/store/addToCart.js
create cart, users can add items to the cart and navigate to the cart page.
> Cart component

- client/components/AllProducts.js
- script/seed.js
- server/api/products.js
- server/db/index.js
- server/db/models/Category.js
- server/db/models/User.js
Created category model, updated the seed file, and included Category in the API route for All Products. Users are now able to filter by category via the dropdown including an All Categories option to reset the filter. Also added a link for All Products view for each product to navigate to single page view.
> All products filter, Category model 

- client/components/AllProducts.js
Fixed all products bug (parentheses issue)
> fix parentheses bug in AllProducts.js

- client/store/addToCart.js
- server/db/index.js
- server/db/models/Lineitem.js
create lineitem model to create the cart eventually and also order. This model will be used in User methods to create the cart in the user methods
> Lineitem model

- client/components/Cart.js
- server/api/cart.js
- server/api/index.js
Added 3 backend routes (2 pending Orders)
> Created 3 backend cart routes and 2 pending order routes

- server/db/index.js
- server/db/models/Lineitem.js
- server/db/models/Order.js
- server/db/models/UserCartMethods.js
user methods for cart - getCart, addToCart and removeFromCart created
> user method ready for review

- client/Routes.js
- client/components/Navbar.js
- server/api/cart.js
- server/db/index.js
- server/db/models/Lineitem.js
- server/db/models/Order.js
- server/db/models/User.js
have products and cart link available when a user is logged in
> Logged in User access to products and cart

- script/seed.js
- server/api/cart.js
user methods works and able to save to the database and retrieve info from database
> Testing user methods

- script/seed.js
> minor changes made to the associations

- client/components/AddToCart.js
- client/components/Cart.js
- client/components/RemoveFromCart.js
- client/store/addToCart.js
- client/store/cart.js
- client/store/index.js
- server/api/cart.js
- server/db/index.js
- server/db/models/UserCartMethods.js
this is just for us to work on a working website before the weekend!
> we are aware cart.js needs work, in progress

- client/components/Cart.js
- client/components/Navbar.js
- client/store/cart.js
- server/api/cart.js
- server/db/models/UserCartMethods.js
cart is working where you can increment and decrement the quantity and also delete the line item. 
Navbar - cart now updates with number of items currently in the cart!
> cart is working and cart on Navbar updates accordingly with cart items

- client/components/AddToCart.js
- client/components/Admin/AddCategory.js
- client/components/Admin/AdminProducts.js
- client/components/AllProducts.js
- client/components/Navbar.js
- client/store/allProducts.js
- client/store/categories.js
- client/store/index.js
- public/style.css
- server/api/categories.js
- server/api/index.js
- server/api/products.js
- server/db/models/Product.js
Has a working form to add a new product (includes categories); has a working form to add new categories as well as remove existing ones.
> Admin Dashboard: All Products Forms

- client/Routes.js
- client/components/AllOrders.js
- client/components/Cart.js
- client/components/Checkout.js
- client/components/SingleProduct.js
- client/store/cart.js
- client/store/index.js
Danbee was having a git issue so I cut and pasted her code on my machine and we also fixed several bugs.
> several bug fixes
